### ISSUE TITLE
udp and tcp peer addr missing from wat

### ISSUE THREAD

**Issue by sid-707** [lunatic-solutions/lunatic#174]
Hey everyone,

I noticed that [`tcp_peer_addr`](https://github.com/lunatic-solutions/lunatic-rs/blob/main/src/host/api.rs#L79) and [`udp_peer_addr`](https://github.com/lunatic-solutions/lunatic-rs/blob/main/src/host/api.rs#L80) used in `lunatic-rs` are missing from the[ `wat/all_imports.wat` file](https://github.com/lunatic-solutions/lunatic/blob/main/wat/all_imports.wat).

Could this be why I'm getting an `Error: unknown import: 'lunatic::networking::udp_peer_addr'` when I run `cargo test` in `lunatic-rs`?

If yes, I can make a PR for this.

**Comment by bkolobara** [comment]
Yes, we should add this 2 functions to `wat/all_imports.wat`.

However, this error is probably caused because you are using lunatic 0.12, the `tcp_peer_addr` and `udp_peer_addr` have not yet been released (are coming in 0.13). You could install the vm from github (`cargo install --git https://github.com/lunatic-solutions/lunatic`) to get access to them.

Also don't forget to update your "runner" setting in `.cargo/config.toml` to `lunatic run`, because the CLI arguments changed slightly.

**Comment by sid-707** [comment]
That makes sense. Thank you @bkolobara.
