### ISSUE TITLE
lunatic::net::resolve no longer seems to work

### ISSUE THREAD

**Issue by SteveSandersonMS** [lunatic-solutions/lunatic#61]
This looks like a very exciting project!

I tried the following example code [from the repo](https://github.com/lunatic-solutions/rust-lib/blob/264816e4ac3034e3073f43ec35b4ee460278a1dd/examples/resolve.rs):

```rust
use lunatic::net;

fn main() {
    let wikipedia = net::resolve("wikipedia.org:80").unwrap();
    for addr in wikipedia {
        println!("wikipedia.org resolves to {:?}", addr);
    }
}
```

but it fails with:

```
thread 'async-std/runtime' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/blocking/pool.rs:84:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
```

This is using:

 * Lunatic 0.6.1 from [releases](https://github.com/lunatic-solutions/lunatic/releases)
 * The lunatic crate version 0.7.0 or 0.6.1 (I tried both)
 * On Windows or Linux (I tried both)

Maybe it's related to the recent change to "[switch from tokio.rs to async_std](https://github.com/lunatic-solutions/lunatic/commit/e4b5ce932fb3265a1183f3b264268e530fc2a58e)". But should this API still be expected to work? Is there an alternative?

**Comment by bkolobara** [comment]
Thanks for reporting this! You are right, this was caused by the switch to `async_std`.

The processes are not running anymore inside of a tokio context and the [`tokio::net::lookup_host` call](https://github.com/lunatic-solutions/lunatic/blob/main/src/api/networking.rs#L213) fails. `async_std` doesn't have a DNS lookup function, so I would just replace this here with [smol's resolve](https://docs.rs/smol/1.2.5/smol/net/fn.resolve.html). The API is similar.

We can also remove the `net` feature from the tokio dependency too, this was the last function requiring it.

**Comment by SteveSandersonMS** [comment]
Fantastic - thanks very much for fixing this!

**Comment by bkolobara** [comment]
@SteveSandersonMS I also pushed a new release out (`0.6.2`) fixing this if you don't feel like building from source the VM.
