### ISSUE TITLE
Refactor into workspace

### ISSUE THREAD

**Issue by teymour-aldridge** [lunatic-solutions/lunatic#87]
It might be worth refactoring Lunatic so that the API is defined in separate crates, which can then be activated through feature flags (so that we can add more experimental APIs that can be excluded from more stable builds).

It might also be worth bringing the `rust-lib` into the main repo, so that it can be tested in tandem with the runtime.

**Comment by bkolobara** [comment]
This is something that I have on my todo list for a long time. It requires a bit of refactoring for us to be able to pull the host functions out into separate crates.

And I would also like to bring `rust-lib` and `lunatic-as` into the same repository, so that we can sync up the tests. I'm not sure what the ideal setup would look like. I imagine that we could get away with just a bash script that `cd`s into the right folder, builds the `vm`, runs all tests for it and then uses the `vm` to test all guest libraries. So that we don't need to introduce another dependency, like make.

I will take onto this task as soon as I'm done with the current work inside of the `rust-lib`.

**Comment by teymour-aldridge** [comment]
> And I would also like to bring rust-lib and lunatic-as into the same repository, so that we can sync up the tests. I'm not sure what the ideal setup would look like. I imagine that we could get away with just a bash script that cds into the right folder, builds the vm, runs all tests for it and then uses the vm to test all guest libraries. So that we don't need to introduce another dependency, like make.

I think just bash scripts would work, and if not maybe a Rust test which builds the libraries and performs the tests? Otherwise something like https://github.com/sagiegurari/cargo-make is a (in my view) more human-friendly `make` alternative.

**Comment by jtenner** [comment]
> And I would also like to bring rust-lib and lunatic-as into the same repository, so that we can sync up the tests.

Is this really necessary? I'm really happy with the way things currently are, and don't mind standardizing tests in isolated repos.

**Comment by bkolobara** [comment]
> Is this really necessary? I'm really happy with the way things currently are, and don't mind standardizing tests in isolated repos.

I'm not that happy with the current situation. For example, changes to the tcp read/write timeout code slightly broke the rust library and this can't be detected with the current setup. Currently we depend on a released version of the vm to test the libraries. If there is a breaking change in the host functions it's impossible to catch it inside of the libraries until we have a release.

Only after we push out a release can we see the tests failing. This is not ideal, and it is only going to get worse once we have multiple languages supported and more people working asynchronously on different parts that are not aware of all changes. It would also force us to address every breaking change in the host functions right away.

**Comment by teymour-aldridge** [comment]
Maybe we can start with at least moving the Rust library to the monorepo and the AssemblyScript one later?
